# Chained Assignment and Views verses Copies

## Imports

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import random
from random import gauss

#enable copy on write (CoW) mode in pandas to avoid chained indexing problems
# pd.set_option("mode.copy_on_write", True)

# Create a dataframe

In [56]:
df = pd.DataFrame([list('abcd'),
                     list('efgh'),
                     list('ijkl'),
                     list('mnop')],
                    columns=pd.MultiIndex.from_product([['one', 'two'],
                                                        ['first', 'second']]))
df

    one          two
  first second first second
0     a      b     c      d
1     e      f     g      h
2     i      j     k      l
3     m      n     o      p

## Chained index, may return a copy, or a slice

In [57]:
df1=df['one']['second']
df1

0    b
1    f
2    j
3    n
Name: second, dtype: object

In [58]:
df1._is_view  #true
df1._is_copy  #weak ref


df1.values.base
# df.values.base
# df1.values.base
# df.values.base is df1.values.base  #true

array([['a', 'e', 'i', 'm'],
       ['b', 'f', 'j', 'n'],
       ['c', 'g', 'k', 'o'],
       ['d', 'h', 'l', 'p']], dtype=object)

In [31]:
# hex(id(df))

### As long as you dont alter a chained index then no problem

In [59]:
df['one']['second'][3]

'n'

### Alter it, BOOM!

In [60]:
#change df1, 
df1[0]=5.5
df1._is_view

# df1
df

    one          two
  first second first second
0     a      b     c      d
1     e      f     g      h
2     i      j     k      l
3     m      n     o      p

In [61]:
#notice that this change also does not stick 
df['one']['second'] = 3
# the above expands to the following
# df.__getitem__('one').__setitem__('second',3)
df

/tmp/ipykernel_1373686/3816245590.py:2: ChainedAssignmentError: A value is trying to be set on a copy of a DataFrame or Series through chained assignment.
When using the Copy-on-Write mode, such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy.

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['one']['second'] = 3

    one          two
  first second first second
0     a      b     c      d
1     e      f     g      h
2     i      j     k      l
3     m      n     o      p

## Fix the chained index

In [62]:
#this one works
df.loc[:,('one','second')]=9
df

    one          two
  first second first second
0     a      9     c      d
1     e      9     g      h
2     i      9     k      l
3     m      9     o      p

# Copy or view?

In [63]:
df = pd.DataFrame([[1,2,3,4],[5,6,7,8]], index = ['row1','row2'], 
        columns = ['a','b','c','d'])
df2 = df.iloc[0:2, :]
df3 = df.loc[df['a'] == 1, :]

df
df2
df3

      a  b  c  d
row1  1  2  3  4

In [64]:
# df is neither copy nor view
print(f'df {df._is_view}, {df._is_copy}')

# df2 is a view AND a copy
print(f'df2 {df2._is_view}, {df2._is_copy}')

# # df3 is not a view, but a copy
print(f'df3 {df3._is_view}, {df3._is_copy}')

# #lets see what the addresses of these dataframes are
print(f'df->{hex(id(df))}, df2->{hex(id(df2))}, df3->{hex(id(df3))}')

df False, None
df2 True, <weakref at 0x7fa76dbe1210; to 'DataFrame' at 0x7fa76dbca5d0>
df3 False, <weakref at 0x7fa76dbe1210; to 'DataFrame' at 0x7fa76dbca5d0>
df->0x7fa76dbca5d0, df2->0x7fa76dbd9b50, df3->0x7fa76dbdbe50

In [65]:
#changes stick
df2.iloc[0,0]=99
df2
df

      a  b  c  d
row1  1  2  3  4
row2  5  6  7  8

In [66]:
df3

      a  b  c  d
row1  1  2  3  4

In [67]:
df2.values.base

array([[99,  5],
       [ 2,  6],
       [ 3,  7],
       [ 4,  8]])

In [70]:
#change the underlying numpy array memory layout (go from an int to a string), it stops working
df2.iloc[0,0]='a'
df2
df

      a  b  c  d
row1  1  2  3  4
row2  5  6  7  8

In [71]:
# df2 is a view AND a copy
print(f'df2 {df2._is_view}, {df2._is_copy}')

df2 False, <weakref at 0x7fa76dbe1210; to 'DataFrame' at 0x7fa76dbca5d0>

## ARRRGGGGHHH! This is awful (and it's been that way for years!).  <br><mark>You could force it to be a copy, then you always know what it is.<br> Or you could enable copy on write (CoW), see line in first cell.  This will be default behaviour from Pandas 3.0 on

In [72]:
df4=df.copy()
print(f'df4 {df4._is_view}, {df4._is_copy}')
df4

df4 False, None

      a  b  c  d
row1  1  2  3  4
row2  5  6  7  8

# Chained indexing in 2 lines

In [73]:
def get_data():
    df = pd.DataFrame({'A': range(0, 5), 
                       'B': range(10, 15),
                       'C': range(100, 105)})
    return df
X = get_data()
X

# #as long as you dont alter it does not matter
X[X['B'] > 12]['C']
# #alter it this way, you get the error
X[X['B'] > 12]['C'] = 999
X
#this works
X.loc[X['B'] > 12,'C' ]=999
X

/tmp/ipykernel_1373686/4006091351.py:12: ChainedAssignmentError: A value is trying to be set on a copy of a DataFrame or Series through chained assignment.
When using the Copy-on-Write mode, such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy.

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[X['B'] > 12]['C'] = 999

   A   B    C
0  0  10  100
1  1  11  101
2  2  12  102
3  3  13  999
4  4  14  999

In [74]:
# create a new DataFrame based on the filtered original
temp = X.loc[X['C'] > 101]
temp.loc[2, 'C'] = 999

## From stackoverflow
https://stackoverflow.com/questions/26879073/checking-whether-data-frame-is-copy-or-view-in-pandas

In [75]:
# Make two data frames that are views of same data.
df = pd.DataFrame([[1,2,3,4],[5,6,7,8]], index = ['row1','row2'], 
       columns = ['a','b','c','d'])
df2 = df.iloc[0:2,:]
display(df)

# Demonstrate they are views:
df.iloc[0,0] = 99
display(df)

print(f'df2.iloc[0,0] is {df2.iloc[0,0]}')

# Now try and compare the id on values attribute
# Different despite being views! 
print(f'id(df)  is {hex(id(df))}')
print(f'id(df.values)  is {hex(id(df.values))}')
print(f'id(df2.values) is {hex(id(df2.values))}')
print()
print(f'df2._is_view is {df2._is_view}')
print(f'df2._is_copy is {df2._is_copy}')
print(f'df._is_view is {df._is_view}')
print(f'df._is_copy is {df2._is_copy}')
print()
# And we can of course compare df and df2
print(f'df is df2 is {df is df2}')
print(f'df.values.base is df2.values.base is {df.values.base is df2.values.base}')

      a  b  c  d
row1  1  2  3  4
row2  5  6  7  8

       a  b  c  d
row1  99  2  3  4
row2   5  6  7  8

df2.iloc[0,0] is 1
id(df)  is 0x7fa76dbf85d0
id(df.values)  is 0x7fa76dbd1b30
id(df2.values) is 0x7fa76dbd27f0

df2._is_view is True
df2._is_copy is <weakref at 0x7fa76dbe30b0; to 'DataFrame' at 0x7fa76dbf85d0>
df._is_view is False
df._is_copy is <weakref at 0x7fa76dbe30b0; to 'DataFrame' at 0x7fa76dbf85d0>

df is df2 is False
df.values.base is df2.values.base is False