## Random Forest- tuning parameters and cross validation
See <a href="https://www.kaggle.com/dansbecker/random-forests">Random Forests</a> tutorial from Kaggle's excellent (and short) <a href="https://www.kaggle.com/learn/intro-to-machine-learning">Intro to Machine Learning</a> course

In [23]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Load Data

In [ ]:
# Download once (won't re-download if file exists)
import os, subprocess, shutil, urllib.request
DATA_URL = "https://raw.githubusercontent.com/CNUClasses/DATA301_CODE/master/week_9/melb_data_clean.csv"
DATA_PATH = "melb_data_clean.csv"

if os.path.exists(DATA_PATH):
    print(f"{DATA_PATH} already exists — skipping download.")
else:
    urllib.request.urlretrieve(DATA_URL, DATA_PATH)

In [24]:
#this data was generated in 91_randomforest_INCLASS_SOLUTION.ipynb
#its just the original dataset with some columns removed and all NaNs fixed
df = pd.read_csv("./melb_data_clean.csv")
# df.head()
print(f'there are {len(df)} rows in df')

there are 13580 rows in df

In [25]:
#what types are we dealing with
df.dtypes

Rooms             int64
Bathroom        float64
Landsize        float64
BuildingArea    float64
Suburb           object
YearBuilt       float64
Lattitude       float64
Longtitude      float64
Car             float64
Price           float64
dtype: object

In [26]:
df.head()

,Rooms,Bathroom,Landsize,BuildingArea,Suburb,YearBuilt,Lattitude,Longtitude,Car,Price
0,2,1.0,202.0,103.0,Abbotsford,1945.0,-37.7996,144.9984,1.0,1480000.0
1,2,1.0,156.0,79.0,Abbotsford,1900.0,-37.8079,144.9934,0.0,1035000.0
2,3,2.0,134.0,150.0,Abbotsford,1900.0,-37.8093,144.9944,0.0,1465000.0
3,3,2.0,94.0,103.0,Abbotsford,1945.0,-37.7969,144.9969,1.0,850000.0
4,4,1.0,120.0,142.0,Abbotsford,2014.0,-37.8072,144.9941,2.0,1600000.0

In [27]:
y=df['Price']
df.drop(columns=['Price'],inplace=True);

## Split the dataset

In [28]:
from sklearn.model_selection import train_test_split
train_X, val_X, train_y, val_y = train_test_split(df, y,random_state = 0)

### Preprocess?
Cheated a bit and preprocessed in 91_randomforest_INCLASS_SOLUTION notebook.  Except for Suburb.  Lets use Sklearn's built in Ordinal encoder (remember it does not matter to a random forest whether you treat a catagorical as ordinal or nominal, they are sensitive to high cardinality categoricals though)

Calculate (fit) the transformer on the training set, then fit it to both the Train and validation sets.

This avoids data leakage from the Validation set into the training set.

In [29]:
#first what are we fitting Categerical encoder to? (object columns), in this case 'Suburb'
df.dtypes

Rooms             int64
Bathroom        float64
Landsize        float64
BuildingArea    float64
Suburb           object
YearBuilt       float64
Lattitude       float64
Longtitude      float64
Car             float64
dtype: object

In [30]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()

#WHEN IT FAILS BELOW UNCOMMENT THIS LINE
# when we see a value in the val set thats not seen in the training set 
enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

#fit to train set ONLY
enc.fit(train_X[["Suburb"]])

#transform both the train AND THE VAL SET
train_X[["Suburb"]]=enc.transform(train_X[["Suburb"]]);

val_X[["Suburb"]]=enc.transform(val_X[["Suburb"]]);

In [66]:
s_train=set(train_X[["Suburb"]].values.flatten())
s_val=set(val_X[["Suburb"]].values.flatten())

#these are the suburbs in the validation set that are not in the training set
#this will cause the ordinal encoder to fail unless we set a special flag value (see above)
print(f'Number of suburbs in validation set not in training set: {len(s_val - s_train)} whose value is {s_val - s_train}')

Number of suburbs in validation set not in training set: 1 whose value is {np.float64(-1.0)}

In [32]:
enc.get_params()

{'categories': 'auto',
 'dtype': numpy.float64,
 'encoded_missing_value': nan,
 'handle_unknown': 'use_encoded_value',
 'max_categories': None,
 'min_frequency': None,
 'unknown_value': -1}

In [33]:
#what ere the categories?
enc.categories_

[array(['Abbotsford', 'Aberfeldie', 'Airport West', 'Albanvale',
        'Albert Park', 'Albion', 'Alphington', 'Altona', 'Altona Meadows',
        'Altona North', 'Ardeer', 'Armadale', 'Ascot Vale', 'Ashburton',
        'Ashwood', 'Aspendale', 'Aspendale Gardens', 'Avondale Heights',
        'Bacchus Marsh', 'Balaclava', 'Balwyn', 'Balwyn North',
        'Bayswater', 'Bayswater North', 'Beaconsfield', 'Beaumaris',
        'Bellfield', 'Bentleigh', 'Bentleigh East', 'Berwick',
        'Black Rock', 'Blackburn', 'Blackburn North', 'Blackburn South',
        'Bonbeach', 'Boronia', 'Box Hill', 'Braybrook', 'Briar Hill',
        'Brighton', 'Brighton East', 'Broadmeadows', 'Brookfield',
        'Brooklyn', 'Brunswick', 'Brunswick East', 'Brunswick West',
        'Bulleen', 'Bullengarook', 'Bundoora', 'Burnley', 'Burnside',
        'Burnside Heights', 'Burwood', 'Burwood East', 'Cairnlea',
        'Camberwell', 'Campbellfield', 'Canterbury', 'Carlton',
        'Carlton North', 'Carnegie', 'Caroline Springs', 'Carrum',
        'Carrum Downs', 'Caulfield', 'Caulfield East', 'Caulfield North',
        'Caulfield South', 'Chadstone', 'Chelsea', 'Chelsea Heights',
        'Cheltenham', 'Chirnside Park', 'Clarinda', 'Clayton',
        'Clayton South', 'Clifton Hill', 'Coburg', 'Coburg North',
        'Collingwood', 'Coolaroo', 'Craigieburn', 'Cranbourne',
        'Cranbourne North', 'Cremorne', 'Croydon', 'Croydon Hills',
        'Croydon North', 'Croydon South', 'Dallas', 'Dandenong',
        'Dandenong North', 'Deepdene', 'Deer Park', 'Delahey', 'Derrimut',
        'Diamond Creek', 'Diggers Rest', 'Dingley Village', 'Docklands',
        'Doncaster', 'Doncaster East', 'Donvale', 'Doreen', 'Doveton',
        'Eaglemont', 'East Melbourne', 'Edithvale', 'Elsternwick',
        'Eltham', 'Eltham North', 'Elwood', 'Emerald', 'Endeavour Hills',
        'Epping', 'Essendon', 'Essendon North', 'Essendon West',
        'Fairfield', 'Fawkner', 'Ferntree Gully', 'Fitzroy',
        'Fitzroy North', 'Flemington', 'Footscray', 'Forest Hill',
        'Frankston', 'Frankston North', 'Frankston South', 'Gardenvale',
        'Gisborne', 'Gladstone Park', 'Glen Huntly', 'Glen Iris',
        'Glen Waverley', 'Glenroy', 'Gowanbrae', 'Greensborough',
        'Greenvale', 'Hadfield', 'Hallam', 'Hampton', 'Hampton East',
        'Hampton Park', 'Hawthorn', 'Hawthorn East', 'Heathmont',
        'Heidelberg', 'Heidelberg Heights', 'Heidelberg West', 'Highett',
        'Hillside', 'Hoppers Crossing', 'Hughesdale', 'Huntingdale',
        'Hurstbridge', 'Ivanhoe', 'Ivanhoe East', 'Jacana', 'Kealba',
        'Keilor', 'Keilor Downs', 'Keilor East', 'Keilor Lodge',
        'Keilor Park', 'Kensington', 'Kew', 'Kew East', 'Keysborough',
        'Kilsyth', 'Kings Park', 'Kingsbury', 'Kingsville', 'Knoxfield',
        'Kooyong', 'Kurunjang', 'Lalor', 'Langwarrin', 'Lower Plenty',
        'Maidstone', 'Malvern', 'Malvern East', 'Maribyrnong', 'McKinnon',
        'Meadow Heights', 'Melbourne', 'Melton', 'Melton South',
        'Melton West', 'Mentone', 'Mernda', 'Middle Park', 'Mill Park',
        'Mitcham', 'Mont Albert', 'Montmorency', 'Montrose',
        'Moonee Ponds', 'Moorabbin', 'Mooroolbark', 'Mordialloc',
        'Mount Evelyn', 'Mount Waverley', 'Mulgrave', 'Murrumbeena',
        'Narre Warren', 'New Gisborne', 'Newport', 'Niddrie', 'Noble Park',
        'North Melbourne', 'North Warrandyte', 'Northcote', 'Notting Hill',
        'Nunawading', 'Oak Park', 'Oakleigh', 'Oakleigh East',
        'Oakleigh South', 'Officer', 'Ormond', 'Pakenham', 'Parkdale',
        'Parkville', 'Pascoe Vale', 'Plumpton', 'Point Cook',
        'Port Melbourne', 'Prahran', 'Preston', 'Princes Hill',
        'Reservoir', 'Richmond', 'Riddells Creek', 'Ringwood',
        'Ringwood East', 'Ringwood North', 'Ripponlea', 'Rosanna',
        'Rowville', 'Roxburgh Park', 'Sandhurst', 'Sandringham',
        'Scoresby', 'Seabrook', 'Seaford', 'Seaholme', 'Seddon', 'Silvan',
        'Skye', 'South Kingsville', 'South Melbourne', 'South Morang',
        'South Yarra', 'Southbank', 'Spotswood', 'Springvale',
        'Springvale South', 'St Albans', 'St Helena', 'St Kilda',
        'Strathmore', 'Strathmore Heights', 'Sunbury', 'Sunshine',
        'Sunshine North', 'Sunshine West', 'Surrey Hills', 'Sydenham',
        'Tarneit', 'Taylors Hill', 'Taylors Lakes', 'Templestowe',
        'Templestowe Lower', 'The Basin', 'Thomastown', 'Thornbury',
        'Toorak', 'Travancore', 'Truganina', 'Tullamarine', 'Vermont',
        'Vermont South', 'Viewbank', 'Wallan', 'Wantirna',
        'Wantirna South', 'Warrandyte', 'Waterways', 'Watsonia',
        'Watsonia North', 'Werribee', 'West Footscray', 'West Melbourne',
        'Westmeadows', 'Wheelers Hill', 'Whittlesea', 'Williams Landing',
        'Williamstown', 'Williamstown North', 'Windsor', 'Wollert',
        'Wyndham Vale', 'Yallambie', 'Yarra Glen', 'Yarraville'],
       dtype=object)]

In [34]:
#here are the encoded names
train_X[['Suburb']][:5]

       Suburb
664      21.0
3270    149.0
3873    182.0
13170   115.0
1730     61.0

In [35]:
# want to get back the original names? (compare to the above train_X.head())
enc.inverse_transform(train_X[["Suburb"]])[:5]

array([['Balwyn North'],
       ['Heidelberg Heights'],
       ['Malvern East'],
       ['Epping'],
       ['Carnegie']], dtype=object)

### What's the average house price?

In [69]:
#for whole dataset
y.mean()

np.float64(1075684.079455081)

###  Train a random forest regressor, use default hyperparameters to get a baseline
Scikitlearn estimators work the same way,;
1. Fit estimator to the training data
2. Generate predictions on validation data
3. Use an error metric to determine how good model is

In [70]:
from sklearn.metrics import mean_absolute_error
def evalmodel(model,X,y):
    '''
    just prints mean_absolute_error
    '''
    preds = model.predict(X)
    mae=mean_absolute_error(y, preds)
    print(f'Mean Absolute Error={mae}')
    return mae

In [71]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

In [72]:
#1. Fit estimator to the training data
forest_model = RandomForestRegressor(random_state=42, n_estimators=20)
# forest_model = RandomForestRegressor( {'random_state':42,'n_estimators': 120, 'max_depth': 34, 'min_samples_split': 3, 'min_samples_leaf': 2})
forest_model=forest_model.fit(train_X, train_y)

# 2. Generate predictions on validation data
preds = forest_model.predict(val_X)

# 3. Use an error metric to determine how good model is
# print(mean_absolute_error(val_y, preds))
base_mae=evalmodel(forest_model,val_X,val_y)

Mean Absolute Error=180856.44730906797

### Use Optuna to find a good set of hyperparameters for this Random forest

In [40]:
#lets use optuna to tune a subset of these parameters (it may take some time! especially as your dataset and number of features go up)
forest_model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 20,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [41]:
#see the max_depth :None above?  Thats because there are a lot of trees with a lot of different depths
#want to find the tree in the forest with the max depth? See below
max([estimator.tree_.max_depth for estimator in forest_model.estimators_])

38

## Use Optuna to tune hyperparameters

In [73]:
# !conda install -c conda-forge optuna -y

In [74]:
sklearn.model_selection.cross_val_score??

Signature:
sklearn.model_selection.cross_val_score(
    estimator,
    X,
    y=None,
    *,
    groups=None,
    scoring=None,
    cv=None,
    n_jobs=None,
    verbose=0,
    params=None,
    pre_dispatch='2*n_jobs',
    error_score=nan,
)
Source:
@validate_params(
    {
        "estimator": [HasMethods("fit")],
        "X": ["array-like", "sparse matrix"],
        "y": ["array-like", None],
        "groups": ["array-like", None],
        "scoring": [StrOptions(set(get_scorer_names())), callable, None],
        "cv": ["cv_object"],
        "n_jobs": [Integral, None],
        "verbose": ["verbose"],
        "params": [dict, None],
        "pre_dispatch": [Integral, str, None],
        "error_score": [StrOptions({"raise"}), Real],
    },
    prefer_skip_nested_validation=False,  # estimator is not validated yet
)
def cross_val_score(
    estimator,
    X,
    y=None,
    *,
    groups=None,
    scoring=None,
    cv=None,
    n_jobs=None,
    verbose=0,
    params=None,
    pre_dispatch="2*n_jobs",
    error_score=np.nan,
):
    """Evaluate a score by cross-validation.

    Read more in the :ref:`User Guide <cross_validation>`.

    Parameters
    ----------
    estimator : estimator object implementing 'fit'
        The object to use to fit the data.

    X : {array-like, sparse matrix} of shape (n_samples, n_features)
        The data to fit. Can be for example a list, or an array.

    y : array-like of shape (n_samples,) or (n_samples, n_outputs), \
            default=None
        The target variable to try to predict in the case of
        supervised learning.

    groups : array-like of shape (n_samples,), default=None
        Group labels for the samples used while splitting the dataset into
        train/test set. Only used in conjunction with a "Group" :term:`cv`
        instance (e.g., :class:`GroupKFold`).

        .. versionchanged:: 1.4
            ``groups`` can only be passed if metadata routing is not enabled
            via ``sklearn.set_config(enable_metadata_routing=True)``. When routing
            is enabled, pass ``groups`` alongside other metadata via the ``params``
            argument instead. E.g.:
            ``cross_val_score(..., params={'groups': groups})``.

    scoring : str or callable, default=None
        Strategy to evaluate the performance of the `estimator` across cross-validation
        splits.

        - str: see :ref:`scoring_string_names` for options.
        - callable: a scorer callable object (e.g., function) with signature
          ``scorer(estimator, X, y)``, which should return only a single value.
          See :ref:`scoring_callable` for details.
        - `None`: the `estimator`'s
          :ref:`default evaluation criterion <scoring_api_overview>` is used.

        Similar to the use of `scoring` in :func:`cross_validate` but only a
        single metric is permitted.

    cv : int, cross-validation generator or an iterable, default=None
        Determines the cross-validation splitting strategy.
        Possible inputs for cv are:

        - `None`, to use the default 5-fold cross validation,
        - int, to specify the number of folds in a `(Stratified)KFold`,
        - :term:`CV splitter`,
        - An iterable that generates (train, test) splits as arrays of indices.

        For `int`/`None` inputs, if the estimator is a classifier and `y` is
        either binary or multiclass, :class:`StratifiedKFold` is used. In all
        other cases, :class:`KFold` is used. These splitters are instantiated
        with `shuffle=False` so the splits will be the same across calls.

        Refer :ref:`User Guide <cross_validation>` for the various
        cross-validation strategies that can be used here.

        .. versionchanged:: 0.22
            `cv` default value if `None` changed from 3-fold to 5-fold.

    n_jobs : int, default=None
        Number of jobs to run in parallel. Training the estimator and computing
        the score are parallelized over the cross-validation splits.
        ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
        ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
        for more details.

    verbose : int, default=0
        The verbosity level.

    params : dict, default=None
        Parameters to pass to the underlying estimator's ``fit``, the scorer,
        and the CV splitter.

        .. versionadded:: 1.4

    pre_dispatch : int or str, default='2*n_jobs'
        Controls the number of jobs that get dispatched during parallel
        execution. Reducing this number can be useful to avoid an
        explosion of memory consumption when more jobs get dispatched
        than CPUs can process. This parameter can be:

        - ``None``, in which case all the jobs are immediately created and spawned. Use
          this for lightweight and fast-running jobs, to avoid delays due to on-demand
          spawning of the jobs
        - An int, giving the exact number of total jobs that are spawned
        - A str, giving an expression as a function of n_jobs, as in '2*n_jobs'

    error_score : 'raise' or numeric, default=np.nan
        Value to assign to the score if an error occurs in estimator fitting.
        If set to 'raise', the error is raised.
        If a numeric value is given, FitFailedWarning is raised.

        .. versionadded:: 0.20

    Returns
    -------
    scores : ndarray of float of shape=(len(list(cv)),)
        Array of scores of the estimator for each run of the cross validation.

    See Also
    --------
    cross_validate : To run cross-validation on multiple metrics and also to
        return train scores, fit times and score times.

    cross_val_predict : Get predictions from each split of cross-validation for
        diagnostic purposes.

    sklearn.metrics.make_scorer : Make a scorer from a performance metric or
        loss function.

    Examples
    --------
    >>> from sklearn import datasets, linear_model
    >>> from sklearn.model_selection import cross_val_score
    >>> diabetes = datasets.load_diabetes()
    >>> X = diabetes.data[:150]
    >>> y = diabetes.target[:150]
    >>> lasso = linear_model.Lasso()
    >>> print(cross_val_score(lasso, X, y, cv=3))
    [0.3315057  0.08022103 0.03531816]
    """
    # To ensure multimetric format is not supported
    scorer = check_scoring(estimator, scoring=scoring)

    cv_results = cross_validate(
        estimator=estimator,
        X=X,
        y=y,
        groups=groups,
        scoring={"score": scorer},
        cv=cv,
        n_jobs=n_jobs,
        verbose=verbose,
        params=params,
        pre_dispatch=pre_dispatch,
        error_score=error_score,
    )
    return cv_results["test_score"]
File:      ~/anaconda3/envs/data301/lib/python3.11/site-packages/sklearn/model_selection/_validation.py
Type:      function

In [48]:
%%time
import optuna
import sklearn
def objective(trial,X=train_X,y=train_y):
    
    #these are the parameters I want to optimize
    rf_params={
    "n_estimators":trial.suggest_int('n_estimators', 10, 100),
    "max_depth":int(trial.suggest_int('max_depth', 8, 55)),
    "min_samples_split":int(trial.suggest_int('min_samples_split', 2, 10)),
    "min_samples_leaf":int(trial.suggest_int('min_samples_leaf', 1, 10)),
    }
    # Define the model. Pass in params to be tuned
    clf = RandomForestRegressor(random_state=42, **rf_params )  

    #get the cross validation score
    # return sklearn.model_selection.cross_val_score( clf, X, y, n_jobs=-1, cv=3, scoring='mean_absolute_error').mean()  get error no mean absolute error metric
    return sklearn.model_selection.cross_val_score( clf, X, y, n_jobs=-1, cv=3, scoring='neg_mean_absolute_error').mean() 

#object that will optimize the objective
study = optuna.create_study(direction='maximize')

#start optimizing, go for 50 rounds
study.optimize(objective, n_trials=25)

trial = study.best_trial

print('neg_mean_absolute_error: {}'.format(trial.value))
print("Best hyperparameters: {}".format(trial.params))

[I 2026-03-31 13:16:25,458] A new study created in memory with name: no-name-b3028403-0bb2-483e-9682-6ff2c1bb7f4e
[I 2026-03-31 13:16:28,228] Trial 0 finished with value: -194051.65754251092 and parameters: {'n_estimators': 65, 'max_depth': 23, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 0 with value: -194051.65754251092.
[I 2026-03-31 13:16:31,189] Trial 1 finished with value: -187384.698290247 and parameters: {'n_estimators': 85, 'max_depth': 49, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 1 with value: -187384.698290247.
[I 2026-03-31 13:16:33,232] Trial 2 finished with value: -193635.14084919053 and parameters: {'n_estimators': 41, 'max_depth': 50, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 1 with value: -187384.698290247.
[I 2026-03-31 13:16:35,335] Trial 3 finished with value: -188377.7742263313 and parameters: {'n_estimators': 36, 'max_depth': 31, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 1 with value: -187384.698290247.
[I 2026-03-31 13:16:38,054] Trial 4 finished with value: -186682.9331077177 and parameters: {'n_estimators': 53, 'max_depth': 49, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 4 with value: -186682.9331077177.
[I 2026-03-31 13:16:40,702] Trial 5 finished with value: -195648.7652911012 and parameters: {'n_estimators': 83, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 4 with value: -186682.9331077177.
[I 2026-03-31 13:16:41,774] Trial 6 finished with value: -191895.5890768815 and parameters: {'n_estimators': 54, 'max_depth': 43, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 4 with value: -186682.9331077177.
[I 2026-03-31 13:16:42,053] Trial 7 finished with value: -198306.01582931017 and parameters: {'n_estimators': 14, 'max_depth': 48, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 4 with value: -186682.9331077177.
[I 2026-03-31 13:16:43,343] Trial 8 finished with value: -190014.82819742066 and parameters: {'n_estimators': 62, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 4 with value: -186682.9331077177.
[I 2026-03-31 13:16:43,669] Trial 9 finished with value: -218746.09761342767 and parameters: {'n_estimators': 22, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 4 with value: -186682.9331077177.
[I 2026-03-31 13:16:45,585] Trial 10 finished with value: -187071.9897533138 and parameters: {'n_estimators': 73, 'max_depth': 36, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 4 with value: -186682.9331077177.
[I 2026-03-31 13:16:47,972] Trial 11 finished with value: -186457.62820981117 and parameters: {'n_estimators': 94, 'max_depth': 38, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 11 with value: -186457.62820981117.
[I 2026-03-31 13:16:50,481] Trial 12 finished with value: -186522.26694961285 and parameters: {'n_estimators': 93, 'max_depth': 40, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 11 with value: -186457.62820981117.
[I 2026-03-31 13:16:52,901] Trial 13 finished with value: -186896.88726420363 and parameters: {'n_estimators': 99, 'max_depth': 37, 'min_samples_split': 7, 'min_samples_leaf': 1}. Best is trial 11 with value: -186457.62820981117.
[I 2026-03-31 13:16:54,989] Trial 14 finished with value: -189989.83128481914 and parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 11 with value: -186457.62820981117.
[I 2026-03-31 13:16:57,045] Trial 15 finished with value: -186218.88007563376 and parameters: {'n_estimators': 86, 'max_depth': 39, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 15 with value: -186218.88007563376.
[I 2026-03-31 13:16:58,728] Trial 16 finished with value: -187276.12635635285 and parameters: {'n_estimators': 77, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 15 with value: -186218.88007563376.
[I 2026-03-31 13:17:00,683] Trial 17 finished with value: -186594.4441437796 and parameters: {'n_estimators': 86, 'max_depth': 54, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 15 with value: -186218.88007563376.
[I 2026-03-31 13:17:02,476] Trial 18 finished with value: -186594.63920451255 and parameters: {'n_estimators': 73, 'max_depth': 42, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 15 with value: -186218.88007563376.
[I 2026-03-31 13:17:04,360] Trial 19 finished with value: -188388.7740752392 and parameters: {'n_estimators': 91, 'max_depth': 34, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 15 with value: -186218.88007563376.
[I 2026-03-31 13:17:05,911] Trial 20 finished with value: -187103.68067187475 and parameters: {'n_estimators': 65, 'max_depth': 21, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 15 with value: -186218.88007563376.
[I 2026-03-31 13:17:08,301] Trial 21 finished with value: -186434.00366131414 and parameters: {'n_estimators': 96, 'max_depth': 41, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 15 with value: -186218.88007563376.
[I 2026-03-31 13:17:11,308] Trial 22 finished with value: -186179.12720082855 and parameters: {'n_estimators': 100, 'max_depth': 45, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 22 with value: -186179.12720082855.
[I 2026-03-31 13:17:13,317] Trial 23 finished with value: -186023.4825875219 and parameters: {'n_estimators': 78, 'max_depth': 45, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 23 with value: -186023.4825875219.
[I 2026-03-31 13:17:15,101] Trial 24 finished with value: -187242.65280715688 and parameters: {'n_estimators': 78, 'max_depth': 45, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 23 with value: -186023.4825875219.

neg_mean_absolute_error: -186023.4825875219
Best hyperparameters: {'n_estimators': 78, 'max_depth': 45, 'min_samples_split': 4, 'min_samples_leaf': 2}
CPU times: user 384 ms, sys: 58.4 ms, total: 443 ms
Wall time: 49.7 s

In [49]:
#what are the best parameters
trial = study.best_trial
trial.params

{'n_estimators': 78,
 'max_depth': 45,
 'min_samples_split': 4,
 'min_samples_leaf': 2}

In [50]:
sklearn.metrics.get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'd2_absolute_error_score',
 'd2_brier_score',
 'd2_log_loss_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_max_error',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'neg_root_mean_squared_log_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_weighted',
 'top_k_accuracy',
 'v_measure_score']

In [51]:
#not satisfied?  Keep on optimizing from where you left off above
study.optimize(objective, n_trials=10)

[I 2026-03-31 13:17:53,324] Trial 25 finished with value: -185552.8857482016 and parameters: {'n_estimators': 88, 'max_depth': 55, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 25 with value: -185552.8857482016.
[I 2026-03-31 13:17:55,420] Trial 26 finished with value: -185643.95523927585 and parameters: {'n_estimators': 90, 'max_depth': 54, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 25 with value: -185552.8857482016.
[I 2026-03-31 13:17:57,103] Trial 27 finished with value: -186064.37967499797 and parameters: {'n_estimators': 71, 'max_depth': 55, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 25 with value: -185552.8857482016.
[I 2026-03-31 13:17:58,553] Trial 28 finished with value: -190178.15505288637 and parameters: {'n_estimators': 78, 'max_depth': 53, 'min_samples_split': 3, 'min_samples_leaf': 6}. Best is trial 25 with value: -185552.8857482016.
[I 2026-03-31 13:17:59,802] Trial 29 finished with value: -187408.74786670165 and parameters: {'n_estimators': 62, 'max_depth': 52, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 25 with value: -185552.8857482016.
[I 2026-03-31 13:18:00,880] Trial 30 finished with value: -186682.86795956714 and parameters: {'n_estimators': 46, 'max_depth': 46, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 25 with value: -185552.8857482016.
[I 2026-03-31 13:18:02,664] Trial 31 finished with value: -186005.7087985305 and parameters: {'n_estimators': 72, 'max_depth': 55, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 25 with value: -185552.8857482016.
[I 2026-03-31 13:18:04,562] Trial 32 finished with value: -186030.11003917138 and parameters: {'n_estimators': 88, 'max_depth': 55, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 25 with value: -185552.8857482016.
[I 2026-03-31 13:18:06,617] Trial 33 finished with value: -185823.28072657718 and parameters: {'n_estimators': 82, 'max_depth': 51, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 25 with value: -185552.8857482016.
[I 2026-03-31 13:18:08,157] Trial 34 finished with value: -186603.76478076316 and parameters: {'n_estimators': 69, 'max_depth': 51, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 25 with value: -185552.8857482016.

In [52]:
model=RandomForestRegressor(random_state=42, **trial.params)
_=model.fit(train_X, train_y)

# opt_mae=evalmodel(model,val_X,val_y)
opt_mae=evalmodel(model,val_X,val_y)
print(f'percentage improvement over base_mae=%{((base_mae-opt_mae)/base_mae)*100}')

Mean Absolute Error=175130.04606468312
percentage improvement over base_mae=%3.166268789189984

# Optuna visualizations
see <a href="https://www.kaggle.com/bextuychiev/no-bs-guide-to-hyperparameter-tuning-with-optuna">this</a> page for an in depth exploration of Optuna.

In [53]:
#lets see how long it took Optuna to get the best parameters
from optuna.visualization import plot_optimization_history

plotly_config = {"staticPlot": True}

fig = plot_optimization_history(study)
fig.show(config=plotly_config)

It found the best value very quickly

## What was the most important hyperparameters

In [54]:
from optuna.visualization import plot_param_importances

fig = plot_param_importances(study)
fig.show(config=plotly_config)

Max depth is far and away the most important hyperparameter to change
 
A plot like this comes in handy when tuning models with many hyperparameters. For example, you could take a test run of 40–50 trials and plot the parameter importances.

Depending on the plot, you might decide to discard some less important parameters and give a larger search space for other ones, possibly reducing the search time and space.

You can check out <a href="https://optuna.readthedocs.io/en/stable/reference/visualization/index.html">this</a> page for more information on Optuna's supported plot types.

In [158]:
# Plotting the accuracies for each hyperparameter for each trial.
optuna.visualization.plot_slice(study)

In [156]:
#see just 1 countour plot
optuna.visualization.plot_contour(study, params=['min_samples_leaf', 'max_depth'])

In [157]:
# see all contour plots
optuna.visualization.plot_contour(study,params=['max_depth', 'min_samples_split'])